package com.pengji.modules.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysUser<M extends BaseSysUser<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setSubjectId(java.lang.Integer subjectId) {
		set("subjectId", subjectId);
		return (M)this;
	}

	public java.lang.Integer getSubjectId() {
		return getInt("subjectId");
	}

	public M setGradeId(java.lang.Integer gradeId) {
		set("gradeId", gradeId);
		return (M)this;
	}

	public java.lang.Integer getGradeId() {
		return getInt("gradeId");
	}

	public M setLoginName(java.lang.String loginName) {
		set("loginName", loginName);
		return (M)this;
	}

	public java.lang.String getLoginName() {
		return getStr("loginName");
	}

	public M setPassword(java.lang.String password) {
		set("password", password);
		return (M)this;
	}

	public java.lang.String getPassword() {
		return getStr("password");
	}

	public M setNo(java.lang.String no) {
		set("no", no);
		return (M)this;
	}

	public java.lang.String getNo() {
		return getStr("no");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return getStr("name");
	}

	public M setPhone(java.lang.String phone) {
		set("phone", phone);
		return (M)this;
	}

	public java.lang.String getPhone() {
		return getStr("phone");
	}

	public M setUserType(java.lang.String userType) {
		set("userType", userType);
		return (M)this;
	}

	public java.lang.String getUserType() {
		return getStr("userType");
	}

	public M setPhoto(java.lang.String photo) {
		set("photo", photo);
		return (M)this;
	}

	public java.lang.String getPhoto() {
		return getStr("photo");
	}

	public M setLoginIp(java.lang.String loginIp) {
		set("loginIp", loginIp);
		return (M)this;
	}

	public java.lang.String getLoginIp() {
		return getStr("loginIp");
	}

	public M setLoginDate(java.util.Date loginDate) {
		set("loginDate", loginDate);
		return (M)this;
	}

	public java.util.Date getLoginDate() {
		return get("loginDate");
	}

	public M setLoginFlag(java.lang.String loginFlag) {
		set("loginFlag", loginFlag);
		return (M)this;
	}

	public java.lang.String getLoginFlag() {
		return getStr("loginFlag");
	}

	public M setCreateBy(java.lang.Integer createBy) {
		set("createBy", createBy);
		return (M)this;
	}

	public java.lang.Integer getCreateBy() {
		return getInt("createBy");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("createDate", createDate);
		return (M)this;
	}

	public java.util.Date getCreateDate() {
		return get("createDate");
	}

	public M setUpdateBy(java.lang.Integer updateBy) {
		set("updateBy", updateBy);
		return (M)this;
	}

	public java.lang.Integer getUpdateBy() {
		return getInt("updateBy");
	}

	public M setUpdateDate(java.util.Date updateDate) {
		set("updateDate", updateDate);
		return (M)this;
	}

	public java.util.Date getUpdateDate() {
		return get("updateDate");
	}

	public M setRemarks(java.lang.String remarks) {
		set("remarks", remarks);
		return (M)this;
	}

	public java.lang.String getRemarks() {
		return getStr("remarks");
	}

	public M setDelFlag(java.lang.String delFlag) {
		set("delFlag", delFlag);
		return (M)this;
	}

	public java.lang.String getDelFlag() {
		return getStr("delFlag");
	}

}
