package com.pengji.modules.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysOperationRecord<M extends BaseSysOperationRecord<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setUserName(java.lang.String userName) {
		set("userName", userName);
		return (M)this;
	}

	public java.lang.String getUserName() {
		return getStr("userName");
	}

	public M setContent(java.lang.String content) {
		set("content", content);
		return (M)this;
	}

	public java.lang.String getContent() {
		return getStr("content");
	}

	public M setAttachmentId(java.lang.Integer attachmentId) {
		set("attachmentId", attachmentId);
		return (M)this;
	}

	public java.lang.Integer getAttachmentId() {
		return getInt("attachmentId");
	}

	public M setCreateBy(java.lang.Integer createBy) {
		set("createBy", createBy);
		return (M)this;
	}

	public java.lang.Integer getCreateBy() {
		return getInt("createBy");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("createDate", createDate);
		return (M)this;
	}

	public java.util.Date getCreateDate() {
		return get("createDate");
	}

	public M setDataLink(java.lang.String dataLink) {
		set("dataLink", dataLink);
		return (M)this;
	}

	public java.lang.String getDataLink() {
		return getStr("dataLink");
	}

	public M setDelFlag(java.lang.String delFlag) {
		set("delFlag", delFlag);
		return (M)this;
	}

	public java.lang.String getDelFlag() {
		return getStr("delFlag");
	}

	public M setDataId(java.lang.Integer dataId) {
		set("dataId", dataId);
		return (M)this;
	}

	public java.lang.Integer getDataId() {
		return getInt("dataId");
	}

	public M setUpdateBy(java.lang.Integer updateBy) {
		set("updateBy", updateBy);
		return (M)this;
	}

	public java.lang.Integer getUpdateBy() {
		return getInt("updateBy");
	}

	public M setUpdateDate(java.util.Date updateDate) {
		set("updateDate", updateDate);
		return (M)this;
	}

	public java.util.Date getUpdateDate() {
		return get("updateDate");
	}

}
