package com.pengji.modules.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysAttachment<M extends BaseSysAttachment<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setFileName(java.lang.String fileName) {
		set("fileName", fileName);
		return (M)this;
	}

	public java.lang.String getFileName() {
		return getStr("fileName");
	}

	public M setFileExt(java.lang.String fileExt) {
		set("fileExt", fileExt);
		return (M)this;
	}

	public java.lang.String getFileExt() {
		return getStr("fileExt");
	}

	public M setFileLink(java.lang.String fileLink) {
		set("fileLink", fileLink);
		return (M)this;
	}

	public java.lang.String getFileLink() {
		return getStr("fileLink");
	}

	public M setFileSize(java.lang.Long fileSize) {
		set("fileSize", fileSize);
		return (M)this;
	}

	public java.lang.Long getFileSize() {
		return getLong("fileSize");
	}

	public M setCreateBy(java.lang.Integer createBy) {
		set("createBy", createBy);
		return (M)this;
	}

	public java.lang.Integer getCreateBy() {
		return getInt("createBy");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("createDate", createDate);
		return (M)this;
	}

	public java.util.Date getCreateDate() {
		return get("createDate");
	}

	public M setUpdateBy(java.lang.Integer updateBy) {
		set("updateBy", updateBy);
		return (M)this;
	}

	public java.lang.Integer getUpdateBy() {
		return getInt("updateBy");
	}

	public M setUpdateDate(java.util.Date updateDate) {
		set("updateDate", updateDate);
		return (M)this;
	}

	public java.util.Date getUpdateDate() {
		return get("updateDate");
	}

	public M setRemarks(java.lang.String remarks) {
		set("remarks", remarks);
		return (M)this;
	}

	public java.lang.String getRemarks() {
		return getStr("remarks");
	}

	public M setDelFlag(java.lang.String delFlag) {
		set("delFlag", delFlag);
		return (M)this;
	}

	public java.lang.String getDelFlag() {
		return getStr("delFlag");
	}

	public M setFileDomain(java.lang.String fileDomain) {
		set("fileDomain", fileDomain);
		return (M)this;
	}

	public java.lang.String getFileDomain() {
		return getStr("fileDomain");
	}

}
