package com.pengji.modules.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;
import com.pengji.modules.user.SysUser;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("sys_attachment", "id", SysAttachment.class);
		arp.addMapping("sys_data", "id", SysData.class);
		arp.addMapping("sys_dict", "id", SysDict.class);
		arp.addMapping("sys_grade", "id", SysGrade.class);
		arp.addMapping("sys_log", "id", SysLog.class);
		arp.addMapping("sys_menu", "id", SysMenu.class);
		arp.addMapping("sys_operation_record", "id", SysOperationRecord.class);
		arp.addMapping("sys_role", "id", SysRole.class);
		// Composite Primary Key order: menuId,roleId
		arp.addMapping("sys_role_menu", "menuId,roleId", SysRoleMenu.class);
		arp.addMapping("sys_user", "id", SysUser.class);
		// Composite Primary Key order: roleId,userId
		arp.addMapping("sys_user_role", "roleId,userId", SysUserRole.class);
	}
}

