package com.pengji.modules.model;

import com.pengji.modules.model.base.BaseSysAttachment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysAttachment extends BaseSysAttachment<SysAttachment> {
	public static final SysAttachment dao = new SysAttachment().dao();
}
