package com.pengji.modules.model;

import com.pengji.modules.model.base.BaseSysData;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysData extends BaseSysData<SysData> {
	public static final SysData dao = new SysData().dao();
}
