package com.pengji.modules.model;

import com.pengji.modules.model.base.BaseSysGrade;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysGrade extends BaseSysGrade<SysGrade> {
	public static final SysGrade dao = new SysGrade().dao();
}
