package com.pengji.modules.model;

import com.pengji.modules.model.base.BaseSysOperationRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysOperationRecord extends BaseSysOperationRecord<SysOperationRecord> {
	public static final SysOperationRecord dao = new SysOperationRecord().dao();
}
